update container images from v0.9.3 to v0.12
charmed-kubernetes/metallb-operator pull request #27
Opened 2022-10-25 05:27 UTC by SMAK1993

Closes [LP#1994064](https://bugs.launchpad.net/operator-metallb/+bug/1994064) by updating metallb-controller/speaker container images to v0.12

2022-11-08 18:01 UTC, stonepreston requested changes
The integration tests call out specific OCI images when deploying the speaker and controller charms. Those would also need to be updated as well. See [here](https://github.com/charmed-kubernetes/metallb-operator/blob/69059f79a478d291b7f1a952d43a4152b03c7179/bundle/tests/test_bundle.py#L23)

2022-11-08 18:13 UTC, stonepreston submitted a review, later dismissed

2022-11-08 18:13 UTC, stonepreston commented on bundle/tests/test_bundle.py
> +        resources={"metallb-speaker-image": "metallb/speaker:v0.12"},
```suggestion
        resources={"metallb-speaker-image": "metallb/speaker:v0.12"},
        trust=True
```

2022-11-08 18:43 UTC, stonepreston commented
seems like the snap store is having issues today. Will keep running the workflows every now and then to see, charmhub also seems to be struggling

2022-11-09 15:20 UTC, kwmonroe approved these changes

2022-11-09 15:21 UTC, merged